version: "3.7"
services:
  graylog-mongo:
    image: mongo:3
    container_name: graylog-mongo
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${USERDIR}/volumes/graylog/mongo/data:/data
    networks:
      - graylog_proxy
  graylog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: graylog-elasticsearch
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ${USERDIR}/volumes/graylog/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - graylog_proxy
  graylog:
    image: graylog/graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_CONTENT_PACKS_AUTO_LOAD=udp-input-graylog.json
      - GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=true
      - GRAYLOG_CONTENT_PACKS_DIR=data/contentpacks
    links:
      - graylog-mongo
      - graylog-elasticsearch
    container_name: graylog
    restart: always
    volumes:
      - ${USERDIR}/volumes/graylog/data/journal:/usr/share/graylog/data/journal
      - ${USERDIR}/services/graylog/graylog.conf:/usr/share/graylog/data/config/graylog.conf
      - ${USERDIR}/services/graylog/udp-input-graylog.json:/usr/share/graylog/data/contentpacks/udp-input-graylog.json
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    labels:
      - traefik.enable=true
      - traefik.backend=graylog
      - traefik.frontend.rule=Host:graylog.${DOMAINNAME}
      - traefik.port=9000
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=${DOMAINNAME}
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
    networks:
      - traefik_proxy
      - graylog_proxy
    extra_hosts:
      - graylog.${DOMAINNAME}:127.0.0.1
networks:
  graylog_proxy:
    name: graylog_proxy
  traefik_proxy:
    name: traefik_proxy
